version: '3'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: naresh
      WORDPRESS_DB_PASSWORD: naresh
    volumes:
      - ./wordpress-data:/var/www/html

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: naresh
      MYSQL_DATABASE: wordpress
      MYSQL_USER: naresh
      MYSQL_PASSWORD: naresh
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
~                   
