---
- name: tomcat and prerequisite deployment through ansible
  hosts: webserver
  tasks:
    - yum:
        name: "{{item}}"
        state: latest

      with_items:
        - java-1.8.0-openjdk*
        - httpd
        - tomcat
        - tomcat-webapps
        - tomcat-admin-webapps
    - service:
        name: "{{item}}"
        state: started
        enabled: yes
      with_items:
        - tomcat
        - httpd
    - lineinfile:
        path: /etc/tomcat/tomcat-users.xml
        line: <user username="naresh" password="naresh" roles="admin-gui,manager-gui,manager-script"/>
        insertafter: '<tomcat-users>'
      notify:
        - start tomcat
  handlers:
    - name: start tomcat
      service:
        name: tomcat
        state: restarted


